services:
  - type: web
    name: cows-bulls-server
    runtime: node
    buildCommand: npm ci
    startCommand: node server.js
    plan: free
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production